###

GET http://localhost:3000/students


###

POST http://localhost:3000/students
Content-Type: application/json

{
  "name": "Tamir",
  "age": 25,
  "_id": "00000022"

}

###


PUT http://localhost:3000/student


###


DELETE http://localhost:3000/student
