###

GET http://localhost:3000/students


###

GET http://localhost:3000/students


###

POST http://localhost:3000/students
Content-Type: application/json

{
  "name": "Shoham",
  "age": 26,
  "_id": "127"

}

###


PUT http://localhost:3000/students/124
Content-Type: application/json

{
  "name": "BAR HaShoter",
  "age": 27,
  "_id": "124"

}


###


DELETE http://localhost:3000/students/124





### 

POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My Third post",
  "message": "This is my first post",
  "owner": 128
}


### 


GET http://localhost:3000/posts




### 


GET http://localhost:3000/students/127/post


